name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]

  workflow_dispatch:
    push: {branches : ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # template: terminal
          token: ${{ secrets.METRICS_TOKEN }}
          user: techtuner
          config_timezone: Asia/Calcutta
          base: header, repositories
          config_display: columns
          plugin_introduction: no
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_sections: most-used, recently-used
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: jupyter notebook
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 1000
          plugin_languages_threshold: 0%
          plugin_languages_indepth: yes
          commits_authoring: techtuner
          plugin_languages_details: lines, percentage
          plugin_languages_other: no
          plugin_habits: no
          plugin_habits_chart: no
